config/routes.rb
Schoolselection::Application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root :to => 'high_voltage/pages#show', :id => 'home'

  resources :schools do
    collection do 
      get   'compare'      
      get   'switch_tab'
      post  'sort'
    end
    member do 
      post  'favorite'
      post  'unfavorite'
    end
  end

end

app/models/school.rb
class School < ActiveRecord::Base
  # acts_as_gmappable :lat => "lat", :lng => "lng"
  acts_as_mappable  :default_units => :miles, :lat_column_name => :lat, :lng_column_name => :lng
  
  has_many :grade_level_schools
  has_many :grade_levels, :through => :grade_level_schools
  #has_and_belongs_to_many :grade_levels
  belongs_to :assignment_zone
  belongs_to :city
  belongs_to :neighborhood
  belongs_to :parcel
  belongs_to :principal
  belongs_to :state
  has_many :geocode_grade_walkzone_schools, :dependent => :destroy
  
  attr_accessor :eligibility, :eligibility_index
  # before_save :recalculate_school_assignment so if they change a school location or add a school it will be reindexed TODO
  before_save :geocode_address
  before_save :create_permalink
  
  validates_uniqueness_of :name
  
  
  if Rails.env == 'development'
    has_attached_file :image, :styles => {:original => "850x600", :slider => "490x330#", :large => "280x200", :medium => "120x90>", :small => "95x71#", :thumb => "85x63#", :icon => "50x50#"}, :path => "#{Rails.root}/public/system/images/:id/:style/:filename"
  elsif Rails.env == 'production'
    has_attached_file :image, 
                      :styles => {:original => "850x600", :slider => "490x330#", :large => "850x565#", :medium => "120x90>", :small => "95x71#", :thumb => "85x63", :icon => "50x50#"}, 
                      :storage => :s3,
                      :bucket => 'discoverbps',
                      :path => "schools/:id/:style/:filename",
                      :s3_credentials => {
                        :access_key_id => ENV['S3_KEY'],
                        :secret_access_key => ENV['S3_SECRET']
                      }
  end
  
  ##### CLASS METHODS #####
  
  class << self
    def walkzone_schools(geocode, grade_level, geocoded_address)
      schools = self.joins(:geocode_grade_walkzone_schools)
        .where(:geocode_grade_walkzone_schools => {:geocode_id => geocode, :grade_level_id => grade_level})
        .select("geocode_grade_walkzone_schools.transportation_eligible as transportation_eligible")
        .select("schools.*")
        .with_distance(geocoded_address)
        .includes(:grade_level_schools, :city)
        .order('distance ASC')
      [[schools,"Walk Zone",1]].each do |schools,type,index|
        schools.each do |s|
          s.eligibility = type
          s.eligibility_index = index
        end
      end
      schools
    end
  
    def with_distance(address)
      self.joins(:parcel).select("ST_Distance(parcels.geometry, ST_GeomFromText('POINT(#{address.lng} #{address.lat})')) as distance")
    end
  
    def find_all_within_radius(address, radius_in_meters)
      self.joins(:parcel).where("ST_DWithin(parcels.geometry, ST_GeomFromText('POINT(#{address.lng} #{address.lat})'), #{radius_in_meters})")
    end
  end
    
  ##### INSTANCE METHODS #####
  
  def grade(number)
    grade_level_schools.detect {|x| x.grade_number == number}
  end
  
  def gmaps4rails_address
    #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.address}, #{self.city.try(:name)}, #{self.try(:state)}" 
  end
  
  private
  
  def geocode_address
    # boston_bounds = Geokit::Geocoders::GoogleGeocoder.geocode('Boston, MA').suggested_bounds
    geo = Geokit::Geocoders::MultiGeocoder.geocode("#{address}, #{city.try(:name)}, MA, #{zipcode}")
    errors.add(:address, "Could not Geocode address") if !geo.success
    self.lat, self.lng = geo.lat,geo.lng if geo.success
  end
  
  def create_permalink
    string = self.name
    separator = "-"
    max_size = 127
    ignore_words = ['a', 'an', 'the', 'la']
    permalink = string.gsub("'", separator)
    permalink.downcase!
    ignore_words.each do |word|
      permalink.gsub!(/^#{word} /, '')
    end
    permalink.gsub!(/[^a-z0-9]+/, separator)
    permalink = permalink.to(max_size)
    self.permalink = permalink.gsub(/^\\#{separator}+|\\#{separator}+$/, '')
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  
  def index
    set_session_variables
    
    m, @street_number, @street_name = session[:address].try(:match, (/(\d+)\s+(.*)/)).try(:to_a)
    
    if session[:address].blank?
      redirect_to(root_url, alert: "You must enter an address")
    elsif session[:zipcode].blank?
      redirect_to(root_url, alert: "You must enter a zipcode")
    elsif m.blank?
      redirect_to(root_url, alert: "We couldn't locate that address - please try again")
    else
      @address_ranges = AddressRange.find_all_by_search_params(@street_number.to_i, @street_name, session[:zipcode])    
      if @address_ranges.blank?
        redirect_to(root_url, alert: "We couldn't locate that address - please try again.")
      else
        if @address_ranges.size == 1
          shared_variables
          respond_to do |format|
            format.html
            format.js
            format.pdf do
              pdf = SchoolsPdf.new(@all_schools, @grade_levels, @grade_level, @geocoded_address, view_context, session)
              send_data pdf.render, filename: "schools.pdf", type: "application/pdf", disposition: "inline"
            end
          end
        elsif @address_ranges.size > 1
          render 'pages/home'
        end    
      end
    end
  end

  def show
    set_session_variables
    m, @street_number, @street_name = session[:address].try(:match, (/(\d+)\s+(.*)/)).try(:to_a)
    @address_ranges = AddressRange.find_all_by_search_params(@street_number.to_i, @street_name, session[:zipcode])
    shared_variables
    @school = @all_schools.find {|x| x.permalink == params[:id] }

    if @school.eligibility =~ /Walk Zone/
      @map_flag_color = '53e200'
    elsif @school.eligibility =~ /Assignment Zone/
      @map_flag_color = 'fcef08'
    else
      @map_flag_color = 'c8c8c8'
    end

    respond_to do |format|
      format.html
      format.json { render json: @school }
      format.pdf do
        pdf = SchoolPdf.new(@school, @grade_level, view_context, session)
        send_data pdf.render, filename: "#{@school.permalink}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end
  
  def compare
    if session[:address].blank?
      redirect_to(root_url, alert: "You must enter an address")
    elsif session[:zipcode].blank?
      redirect_to(root_url, alert: "You must enter a zipcode")
    else
      @favorite_schools = session[:favorites].map {|x| School.find(x)}
      respond_to do |format|
        format.html
        format.js
      end
    end
  end
  
  ####### AJAX #######
  
  def switch_tab
    respond_to do |format|
      format.js
    end
  end
  
  def favorite
    @school = School.find(params[:id])
    session[:favorites] ||= []
    session[:favorites] << @school.id unless session[:favorites].include?(@school.id)
    session[:favorites].present? ? @favorite_schools = session[:favorites].map {|x| School.find(x)} : @favorite_schools = []
    respond_to do |format|
      format.js
    end
  end
  
  def unfavorite
    @school = School.find(params[:id])
    session[:favorites].delete_if {|x| x == @school.id }
    session[:favorites].present? ? @favorite_schools = session[:favorites].map {|x| School.find(x)} : @favorite_schools = []
    respond_to do |format|
      format.js
    end
  end
  
  def sort
    @favorite_schools = params[:school].map {|x| School.find(x)}
    session[:favorites] = []
    @favorite_schools.each do |school|
      session[:favorites] << school.id
    end
    render :nothing => true
  end
  
  private
  
  def set_session_variables
    session[:address]         = params[:address]
    session[:zipcode]         = params[:zipcode]
    session[:grade_level]     = params[:grade_level]
    session[:sibling_school]  = params[:sibling_school]
  end
  
  def shared_variables
    @address = @address_ranges.first
    @grade_levels = GradeLevel.all
    @grade_level = GradeLevel.find_by_number(session[:grade_level])
    @geocoded_address ||= geocode_address("#{@street_number} #{@street_name}, Boston, MA #{session[:zipcode]}")
    @geocode = @address.geocode
    @assignment_zone = @geocode.assignment_zone
    @walk_zone_schools = School.walkzone_schools(@geocode, @grade_level, @geocoded_address)
    @assignment_zone_schools = @grade_level.assignment_zone_schools(@geocoded_address, @assignment_zone) - @walk_zone_schools
    @citywide_schools = @grade_level.citywide_schools(@geocoded_address, AssignmentZone.citywide) - @walk_zone_schools
    @all_schools = (@walk_zone_schools + @assignment_zone_schools + @citywide_schools)
    session[:favorites].present? ? @favorite_schools = session[:favorites].map {|x| School.find(x)} : @favorite_schools = []
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
  
  def distance(distance)
    "#{distance.to_f.round(2)}&nbsp;miles"
  end
  
  def distance_in_miles_from_meters(distance)
    number_with_precision((distance.to_f / METERS_PER_MILE), :precision => 2)
  end
  
  def walk_time(distance)
    (distance.to_f / WALK_TIME_METERS_PER_MINUTE).floor
  end

  def drive_time(distance)
    (distance.to_f / DRIVE_TIME_METERS_PER_MINUTE).floor
  end
  
  def eligibility_title(school)
    if school.eligibility =~ /Walk Zone/
      "Walk&nbsp;Zone"
    elsif school.eligibility =~ /Assignment Zone/
      "Assignment&nbsp;Zone"
    elsif school.eligibility =~ /Citywide/
      "Citywide"
    end      
  end
        
  include EncodePolyline
  def static_schools_map(width, height)
    zone_boundry = encode_line(simplify_points(@assignment_zone.geometry[0].exterior_ring.points,0.001,0.01))
    image_tag("http://maps.google.com/maps/api/staticmap?" + 
      "size=#{width}x#{height}" + 
      '&zoom=10' +
      "&maptype=roadmap" +
      "&sensor=false" +
      "&markers=size:tiny|color:0x53e200|#{@walk_zone_schools.map {|x|"#{x.lat},#{x.lng}"} * "|" }" +
      "&markers=size:tiny|color:0xfcef08|#{@assignment_zone_schools.map {|x|"#{x.lat},#{x.lng}"} * "|" }" +
      "&markers=size:tiny|color:0xc8c8c8|#{@citywide_schools.map {|x|"#{x.lat},#{x.lng}"} * "|" }" +
      "&path=fillcolor:0xfcef08|color:0x0000ff|weight:1|enc:#{zone_boundry}", 
      :alt => "Map View", :class => 'static-map-image')
  end
  
  def static_school_map(width, height, color)
    "http://maps.google.com/maps/api/staticmap?" + 
    "size=#{width}x#{height}" + 
    '&zoom=14' +
    "&maptype=roadmap" +
    "&sensor=false" +
    "&markers=size:large|color:0x#{color}|#{[@school].map {|x|"#{x.lat},#{x.lng}"} * "|" }"
  end
  
  ####### ALL SCHOOLS MAP #######
    
  def walk_zone_map
      gmaps("markers" => {
        "data" => markers_json, 
        "options" => {"list_container" => "markers_list"}}, 
        "polygons" => {
          "data" => assignment_zones_json, 
          "options" => { 
            "fillColor" => "#ffff00", "fillOpacity" => 0.3, 
            "strokeColor" => "#000000", "strokeWeight" => 1.5, 'strokeOpacity' => 0.6 
          }
        }, 
        "circles" => {"data" => walk_zone_json }, 
        "map_options" => { "provider" => "googlemaps", "auto_adjust" => true }
      )
  end
  
  def walk_zone_json
      [{:lng => @geocoded_address.lng, :lat => @geocoded_address.lat, :radius => @grade_level.walk_zone_radius * METERS_PER_MILE, :fillColor => '#61d60e', :fillOpacity => 0.4, :strokeColor => '#000000', :strokeOpacity => 0.6, :strokeWeight => 1.5}].to_json
  end
  
  def assignment_zones_json
    @assignment_zone.shape_to_json
  end
  
  def markers_json
    array = []
    array << @walk_zone_schools.map {|x| create_listing_hash(x, 'green')}
    array << @assignment_zone_schools.map {|x| create_listing_hash(x, 'yellow')}
    array << @citywide_schools.map {|x| create_listing_hash(x, 'gray')}    
    array << [{
      :sidebar => @geocoded_address.street_address,
      :lng => @geocoded_address.lng, :lat => @geocoded_address.lat,
      :picture => '/assets/icons/home.png',
      :width => '18', :height => '15',
      :marker_anchor => [9, 7]
    }]
    array.flatten.to_json
  end
  
  def create_listing_hash(x, color)
    {
      :lng => x.lng, :lat => x.lat,
      :picture => "/images/#{color}-marker.png",
      :width => '21', :height => '38',
      :shadow_picture => '/images/shadow.png',
      :shadow_width => '43', :shadow_height => '38',
      :shadow_anchor => [10, 33],
      :description => %{
        #{alert(x)}
        <ul class='horizontal-list'>
          <li>#{image_tag(x.image(:thumb), :class => 'rounded-corners')}</li>
          <li>
            <h3 class='bold'>#{x.name}</h3>
            #{x.address}<br />
            #{x.city.try(:name)} MA, #{x.zipcode}<br />
            <strong>#{link_to 'Learn More', school_path(x.permalink, search_params())}</strong>
          </li>
        </ul>
      },
      :sidebar => "#{x.name}"
    }
  end
  
  def alert(x)
    if x.id.to_s == session[:sibling_school]
      "<div id='flash' class='normal bold center yellow-background'>This school qualifies for Sibling Priority</div>"
    elsif x.eligibility =~ /Walk Zone/
      "<div id='flash' class='normal bold center green-background'>This school qualifies for Walk Zone Priority</div>"
    end
  end
end

app/views/schools/_favorite_schools.html.haml
%table.padded.favorite-school
  %tr{:id=>"favorite_school_#{school.id}", :class => 'yellow-background draggable'}
    %td.handle_column
      = image_tag('icons/handle.png')
    %td{:height=>'90px' }
      = image_tag(school.image(:thumb), :class => 'rounded-corners')
    %td.title_column
      %h3.bold= school.name
      %span.italic
        == #{school.address}, #{school.city.try(:name)}
        - if school.phone.present?
          == Phone: #{school.phone}
    %td &nbsp;
    %td{:width=>'340'}
      - if school.preview_hours.present?
        Preview Hours:
        = school.preview_hours
    %td.view_button_column.right_padded
      = link_to "View", school_path(school.permalink, search_params()), :class => 'blue-button'
    %td.favorite_button_column
      = render :partial => 'schools/favorite_button', :locals => {:school => school}

app/views/schools/_favorite_text_button.html.haml
#favorite_text_button
  - if session[:favorites].try(:include?, @school.id)
    = link_to image_tag('star-gray.png', :class => 'star-icon'), unfavorite_school_path(@school.id, address: session[:address], zipcode: session[:zipcode], grade_level: session[:grade_level]), :remote => true, :method => :post, :class => 'gray-button', :title => 'Unfavorite'
    %span.favorites_button_text.bold
      = link_to "Remove from Favorites", unfavorite_school_path(@school.id, address: session[:address], zipcode: session[:zipcode], grade_level: session[:grade_level]), :remote => true, :method => :post
  - else
    = link_to image_tag('star.png', :class => 'star-icon'), favorite_school_path(@school.id, address: session[:address], zipcode: session[:zipcode], grade_level: session[:grade_level]), :remote => true, :method => :post, :class => 'yellow-button', :title => 'Favorite'
    %span.favorites_button_text.bold
      = link_to "Add to My Favorites", favorite_school_path(@school.id, address: session[:address], zipcode: session[:zipcode], grade_level: session[:grade_level]), :remote => true, :method => :post

app/views/schools/_favorites.html.haml
#favorites_sidebar
  %h3.bold My Favorites
  - unless session[:favorites].present?
    To create a customized list of your top schools, click the star button beside each listing.
  - else
    %ol#favorite-list
      - for school in @favorite_schools
        %li
          = school.name
          = link_to image_tag('icons/bullet_delete.png'), unfavorite_school_path(school.id, address: session[:address], zipcode: session[:zipcode], grade_level: session[:grade_level]), :remote => true, :method => :post
    
    = link_to "Compare", compare_schools_path(search_params()), :class => 'blue-button'

app/views/schools/_list_view.html.haml
#sidebar
  #nav
    %h3.bold
      Map View
    = link_to static_schools_map(150, 125), schools_path(search_params(:view => 'map')), :class => 'sidebar-nav'

  #mypicks
    = render :partial => 'favorites'
    
= render :partial => 'layouts/navigation'

#left-column    
  #page
    %h2.bold
      %span.small.nobold.italic
        == Eligible Schools for:&nbsp;
      == #{@street_number} #{@street_name.try(:titleize)}, #{@geocoded_address.city}, #{@geocoded_address.state} / Grade #{session[:grade_level]}
      %span.smaller.nobold
        == &nbsp;#{link_to 'Search Again', page_path('home'), :id => 'search_again'}
    
    .notes.rounded-corners
      = image_tag('icons/lightbulb.png')
      &nbsp;Below are your eligible schools. Click the 'Views' buttons to see more information, or click the column headings to sort the listings.  You can also view your eligible schools on a map by clicking the map icon at right.
    
    %ul#table-nav
      %li Views: 
      %li= link_to 'Overview', switch_tab_schools_path(:tab => 'overview'), :remote => true, :id => 'overview-tab'
      %li= link_to 'Transportation', switch_tab_schools_path(:tab => 'transportation'), :remote => true, :id => 'transportation-tab'
      - if @all_schools.map {|x| x.grade(params[:grade_level]).try(:mcas_ela_advanced) }.try(:compact).present?
        %li= link_to 'Academics', switch_tab_schools_path(:tab => 'academics'), :remote => true, :id => 'academics-tab'
      - if @all_schools.map {|x| x.grade(params[:grade_level]).try(:open_seats) }.try(:compact).present?
        %li= link_to 'Admissions', switch_tab_schools_path(:tab => 'admissions'), :remote => true, :id => 'admissions-tab'
      
    %table#visible-schools.listings.sortable
      %thead
        %tr
          %th.icon_column &nbsp;
          %th.title_column.sorttable School Name
          %th.eligibility_column.tabbable.overview Eligibility<span id="sorttable_sortfwdind">&nbsp;▾</span>
          %th.tabbable.overview.sorttable Transit
          %th.tabbable.overview.sorttable_numeric Distance
          %th.tabbable.overview.sorttable 2011 Hours

          %th.tabbable.transportation.hidden.sorttable Transportation Eligibility
          %th.tabbable.transportation.hidden.sorttable_numeric Distance
          %th.tabbable.transportation.hidden.sorttable_numeric Walk Time*
          %th.tabbable.transportation.hidden.sorttable_numeric Drive Time*

          %th.tabbable.academics.hidden Teachers†
          %th.tabbable.academics.hidden Students†
          %th.tabbable.academics.hidden MCAS English Percentile†
          %th.tabbable.academics.hidden MCAS Math Percentile†

          %th.tabbable.admissions.hidden Open Seats†
          %th.tabbable.admissions.hidden 1st Choices†
          %th.tabbable.admissions.hidden 2nd Choices†
          %th.tabbable.admissions.hidden 3rd Choices†
          %th.tabbable.admissions.hidden.sorttable_numeric Applicants per Open Seat†

          %th{:width=>'50px'} &nbsp;
          %th{:width=>'50px'} &nbsp;

      %tbody
        - if @all_schools.present?
          - @all_schools.each do |school|
            - if session[:favorites].try(:include?, school.id)
              = render :partial => 'schools/school_row', :locals => {:school => school, :row_classes => 'favorited'}
            - else
              = render :partial => 'schools/school_row', :locals => {:school => school, :row_classes => ''}

    %table#download_links
      %tr
        %td{:width=>'24px'}
          == #{raw link_to image_tag('icons/icon_PDF_big.png', :class => 'pdf_icon'), schools_path(:address => params[:address], :zipcode => params[:zipcode], :grade_level => params[:grade_level], :sibling_school => params[:sibling_school], :format => :pdf)} 
        %td{:style => "font-weight: bold; padding: 0;"}
          == #{link_to 'Download PDF', schools_path(:address => params[:address], :zipcode => params[:zipcode], :grade_level => params[:grade_level], :sibling_school => params[:sibling_school], :format => :pdf)}

    #footnotes.italic.small
      * Walk times and drive times are estimates, only.
      %br/
      † Historical data are from the previous school year, unless otherwise noted.
        
  = render :partial => 'layouts/page_footer'

%script
  $(document).ready(function() {
  var yOffset = $("#sidebar").offset().top - 40;
  $(window).scroll(function() {
  if ($(window).scrollTop() > yOffset) {
  $("#sidebar").css({
  'top': 0,
  'position': 'fixed'
  });
  } else {
  $("#sidebar").css({
  'top': yOffset + 'px',
  'position': 'absolute'
  });
  }
  });
  });
      

app/views/schools/_listings_row.html.haml
%tr
  %td
    %h4
      = link_to school.name, school_path(school), :rel => 'facebox'
  %td
    = school.grade_levels.short_string
  %td{:width=>'60px'}
    = school.neighborhood.try(:name)
  %td{:width=>'60px'}
    == #{distance_in_miles_from_meters(school.distance)} mi.
  %td{:width=>'70px'}
    - if type == 'walk_zone'
      == #{walk_time(school.distance)} min.
    - else
      &nbsp;

app/views/schools/_listings_table.html.haml
%table.listings
  %thead
    %tr
      %th School Name
      %th{:width=>'50px'} Grades
      %th{:width=>'60px'} Neighborhood
      %th{:width=>'60px'} Distance
      %th{:width=>'60px'} Walk Time
  %tbody
    - if @walk_zone_schools.present?
      - @walk_zone_schools.each do |school|
        = render :partial => 'listings_row', :locals => {:school => school, :type => 'walk_zone', :color => 'green'}
              
    - if @assignment_zone_schools.present?
      - @assignment_zone_schools.each do |school|
        = render :partial => 'listings_row', :locals => {:school => school, :type => 'assignment_zone', :color => 'yellow'}
    
    - if @citywide_schools.present?
      - @citywide_schools.each do |school|
        = render :partial => 'listings_row', :locals => {:school => school, :type => 'citywide', :color => 'gray'}

app/views/schools/_map_view.html.haml
#sidebar
  #nav
    %h3.bold
      = link_to "List View", schools_path(search_params(:view => 'list')), :class => 'sidebar-nav'
  #mypicks
    = render :partial => 'favorites'
  
= render :partial => 'layouts/navigation'   
#left-column
  #page
    %h2.bold
      %span.small.nobold.italic
        Eligible Schools for:&nbsp;
      == #{@street_number} #{@street_name.try(:titleize)}, #{@geocoded_address.city}, #{@geocoded_address.state} / Grade #{session[:grade_level]}
      %span.smaller.nobold
        == &nbsp;#{link_to 'Search Again', page_path('home')}
    
    .notes.rounded-corners
      = image_tag('icons/lightbulb.png')
      == &nbsp;Below is a map of your eligible schools. The yellow shape represents the #{@assignment_zone.name} Assignment Zone; the flags represent your eligible schools; the house icon is centered on your home address. Click the flags or the school name links to learn more.  Click the 'List View' tab - at right - to return to the previous page.    
    #map
      #map-container
        = walk_zone_map
      #map-list
        #options
          <ul id="markers_list"></ul>
    .clear-both
      %ul.horizontal-list
        %li
          = image_tag('green-marker-medium.png')
          Walk Zone School &nbsp;
        %li
          = image_tag('yellow-marker-medium.png')
          Assignment Zone School &nbsp;
        %li
          = image_tag('gray-marker-medium.png')
          Citywide School
      
  = render :partial => 'layouts/page_footer'
  

app/views/schools/_school_row.html.haml
%tr{:id=>"visible_school_#{school.id}", :class => "#{row_classes}"}
  %td.small_image_column
    = image_tag(school.image(:thumb), :class => 'rounded-corners')
  %td.title_column
    %h4.bold
      = link_to school.name, school_path(school.permalink, search_params())
    %span.italic
      == #{school.address}, #{school.city.try(:name)}

  - grade = school.grade(session[:grade_level])
  
  / OVERVIEW /
  %td.tabbable.overview.large{:sorttable_customkey=>school.eligibility_index}
    =raw school.eligibility.present? ? eligibility_title(school) : '&nbsp;'
    - if params[:sibling_school] == school.id.to_s && School.find(params[:sibling_school].try(:to_i)).present?
      Sibling School
  %td.tabbable.overview.large      
    - if (school.eligibility =~ /Walk Zone/) && !school.transportation_eligible?
      = image_tag('walking.png')
    - else
      - if @grade_level.name == "High"
        = image_tag('city-bus.png')
      - else
        = image_tag('school-bus.png')
  %td.tabbable.overview.large
    =raw school.distance.present? ? "#{distance_in_miles_from_meters(school.distance)}&nbsp;<span class='small'>mi</span>" : '&nbsp;'
  %td.tabbable.overview
    =raw school.grade(session[:grade_level]).try(:hours).present? ? school.grade(session[:grade_level]).try(:hours) : '&nbsp;'
  
  / TRANSPORTATION /
  %td.tabbable.transportation.large.hidden
    - if (school.eligibility =~ /Walk Zone/) && !school.transportation_eligible?
      == #{image_tag('walking.png', :class=> 'transportation-icon')}&nbsp;Walking
    - else
      - if @grade_level.name == "High"
        == #{image_tag('city-bus.png', :class=> 'transportation-icon')}&nbsp;MBTA
      - else
        == #{image_tag('school-bus.png', :class=> 'transportation-icon')}&nbsp;School Bus

  %td.tabbable.transportation.hidden.larger
    =raw school.distance.present? ? "#{distance_in_miles_from_meters(school.distance)} <span class='small'>mi</span>" : '&nbsp;'
  %td.tabbable.transportation.hidden.larger
    - if school.eligibility =~ /Walk Zone/
      =raw school.distance.present? ? "#{walk_time(school.distance)} <span class='small'>min</span>" : '&nbsp;'
    - else
      &nbsp;
  %td.tabbable.transportation.hidden.larger
    =raw school.distance.present? ? "#{drive_time(school.distance)} <span class='small'>min</span>" : '&nbsp;'


  / ACADEMICS /
  %td.tabbable.academics.hidden.larger
    =raw school.teachers_count.present? ? school.teachers_count : '&nbsp;'

  %td.tabbable.academics.hidden.larger
    =raw school.students_count.present? ? school.students_count : '&nbsp;'

  %td.tabbable.academics.hidden.larger
    - if grade.present? && grade.mcas_ela_advanced.present?
      =raw grade.ela_percentile.present? ? grade.ela_percentile : '&nbsp;'

  %td.tabbable.academics.hidden.larger
    - if grade.present? && grade.mcas_math_advanced.present?
      =raw grade.math_percentile.present? ? grade.math_percentile : '&nbsp;'

  / ADMISSIONS /
  %td.tabbable.admissions.hidden.larger
    =raw grade.try(:open_seats) ? grade.open_seats : '&nbsp;'
  %td.tabbable.admissions.hidden.larger
    =raw grade.try(:first_choice) ? grade.first_choice : '&nbsp;'
  %td.tabbable.admissions.hidden.larger
    =raw grade.try(:second_choice) ? grade.second_choice : '&nbsp;'
  %td.tabbable.admissions.hidden.larger
    =raw grade.try(:third_choice) ? grade.third_choice : '&nbsp;'
  %td.tabbable.admissions.hidden.larger
    =raw grade.try(:total_choices) ? "#{number_with_precision(grade.demand, :precision => 0)} : 1" : '&nbsp;'
  
  %td.view_button_column
    = link_to "View", school_path(school.permalink, search_params()), :class => 'blue-button'
  %td.favorite_button_column
    = render :partial => 'schools/favorite_button', :locals => {:school => school}

app/views/schools/favorite.js.erb
$("#favorite_text_button").replaceWith("<%= escape_javascript(render :partial => 'schools/favorite_text_button', :locals => {:school => @school}) %>");
$("#favorite_button_<%= @school.id %>").replaceWith("<%= escape_javascript(render :partial => 'schools/favorite_button', :locals => {:school => @school}) %>");
$("#visible_school_<%= @school.id %>").addClass('favorited');
$('#favorites_sidebar').replaceWith("<%= escape_javascript(render :partial => 'schools/favorites') %>");

app/views/schools/index.html.haml
- if params[:view] == 'map'
  = render :partial => 'map_view'  
- elsif
  = render :partial => 'list_view'  