config/routes.rb
Schoolselection::Application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  root :to => 'high_voltage/pages#show', :id => 'home'

  resources :schools do
    collection do 
      get   'compare'      
      get   'switch_tab'
      post  'sort'
    end
    member do 
      post  'favorite'
      post  'unfavorite'
    end
  end

end

app/views/layouts/_navigation.html.haml
#main-nav
  - if params[:address] && params[:zipcode]
    - if params[:controller] == 'high_voltage/pages' && params[:id] == 'home'
      = link_to 'Search', root_url(search_params()), :class => 'main-nav active'
    - else
      = link_to 'Search', root_url(search_params()), :class => 'main-nav'

    - if params[:controller] == 'schools' && (params[:action] == 'index' || params[:action] == 'show')
      = link_to 'Schools', schools_url(search_params()), :class => 'main-nav active'
    - else
      = link_to 'Schools', schools_url(search_params()), :class => 'main-nav'
  
    - if params[:controller] == 'schools' && params[:action] == 'compare'
      = link_to 'My Favorites', compare_schools_url(search_params()), :class => 'main-nav active'
    - else
      = link_to 'My Favorites', compare_schools_url(search_params()), :class => 'main-nav'
  - else
    = link_to 'Search', root_url(search_params()), :class => 'main-nav active'
    %span.main-nav-off
      Schools
    %span.main-nav-off
      My Favorites

app/views/layouts/_page_footer.html.haml
#page-footer
  = link_to image_tag('BPS-logo-small.png'), 'http://www.bostonpublicschools.org'
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  = link_to image_tag('cfa_logo.png'), 'http://codeforamerica.org'

app/views/layouts/application.html.haml
%html
  %head
    %title Discover BPS
    = stylesheet_link_tag 'screen.css', :media => 'all'
    = stylesheet_link_tag 'print.css', :media => 'print'
    = javascript_include_tag 'application'
    = csrf_meta_tag 
    /[if lt IE 8]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'

  %body
    #container
      #header
        = link_to image_tag('logo-blue.png'), root_url
      #screen
        = yield
      
    = yield :scripts
    
    <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-25443060-1']);
    _gaq.push(['_setDomainName', 'none']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);
    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    </script>
    
    <script type="text/javascript" charset="utf-8">
    var is_ssl = ("https:" == document.location.protocol);
    var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
    document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
    </script>

    <script type="text/javascript" charset="utf-8">
    var feedback_widget_options = {};

    feedback_widget_options.display = "overlay";  
    feedback_widget_options.company = "code_for_america";
    feedback_widget_options.placement = "left";
    feedback_widget_options.color = "#222";
    feedback_widget_options.style = "idea";
    var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
    </script>

    <script type="text/javascript">
    var _kmq = _kmq || [];
    var _kmk = _kmk || '28b265cb5e8ae2b83af26363580813bc71966d6f';
    function _kms(u){
    setTimeout(function(){
    var d = document, f = d.getElementsByTagName('script')[0],
    s = d.createElement('script');
    s.type = 'text/javascript'; s.async = true; s.src = u;
    f.parentNode.insertBefore(s, f);
    }, 1);
    }
    _kms('//i.kissmetrics.com/i.js');
    _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
    </script>